### ISSUE TITLE
Will you share the checkpoint of your relighting diffusion model

### ISSUE THREAD

**Issue by ZiyangYan** [illuminerf/illuminerf_results#1]
Thanks for your nice work, we want to use your RDM as research propose, would you mind share the checkpoint for us?

**Comment by Xiaoming-Zhao** [comment]
Hi, thanks a lot for your interest in our work.

It is impossible for us to release the RDM at this time. The main reason is stated in the README: though we only fine-tune the diffusion model on Objaverse (a public dataset), the base diffusion model is trained on an in-house dataset, which prevents us from open-sourcing.

I apologize for the inconvenience.

**Comment by ZiyangYan** [comment]
> Hi, thanks a lot for your interest in our work.
> 
> It is impossible for us to release the RDM at this time. The main reason is stated in the README: though we only fine-tune the diffusion model on Objaverse (a public dataset), the base diffusion model is trained on an in-house dataset, which prevents us from open-sourcing.
> 
> I apologize for the inconvenience.

thank you for your response
